import { Inter } from "next/font/google";
import "@/styles/reset.css";
import "@/styles/global.css";

import Footer from "../components/footer";
import Header from "../components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextFlix",
  description: "Generated by Muhammed Mustafa Kan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
